baseURL: 'https://beatboxerish.github.io/website-ishan/'
languageCode: 'en-us'
title: 'Home of Ish'
theme: "papermod"
params:
    profileMode:
        enabled: true
        title: "Hello there..." # optional default will be site title
        subtitle: "This tiny space is about me and my perspectives ^_^"
        imageUrl: 'ishan_gif.gif'
        imageTitle: "Images of yours truly"
        imageWidth: 500 # custom size
        imageHeight: 500 # custom size
        buttons:
            - name: About Me
              url: "posts/about-me-03-24"
            - name: Resume
              url: "Short_Resume.pdf"
            - name: All Posts
              url: "posts"
            - name: Writings on the Web
              url: "posts/writings-on-the-web"
    socialIcons:
      - name: "linkedin"
        url: "https://www.linkedin.com/in/ishan-nangia-413571114/"
      - name: "github"
        url: "https://github.com/beatboxerish"
      - name: "instagram"
        url: "https://www.instagram.com/beatboxerish/"
    defaultTheme: 'auto'
